apiVersion: v1
kind: Secret
metadata:
  name: signalrank-secret
type: Opaque
stringData:
  API_KEY: {{ .Values.secretEnv.API_KEY | quote }}
  ENRICHMENT_API_KEY: {{ .Values.secretEnv.ENRICHMENT_API_KEY | quote }}
